import os
import re
from django.core.mail import send_mail
from django.conf import settings

def extract_patient_info(text: str) -> dict:
    """Parse key fields from RAG answer for email formatting."""
    return {"content": text}

def send_rag_email(to_email: str, question: str, answer: str, source: str) -> dict:
    """Agent: formats and sends retrieved info via email."""
    
    # Clean answer (strip internal markers if any)
    clean_answer = answer.strip()
    
    subject = f"NeuroCore Report: {question[:60]}"
    
    body = f"""NeuroCore Medical Records Assistant
{'='*50}

QUERY:
{question}

{'='*50}
RETRIEVED INFORMATION:
{clean_answer}

{'='*50}
SOURCE:
{source if source else 'N/A'}

---
This report was generated by NeuroCore RAG system.
Do not reply to this email.
"""
    try:
        send_mail(
            subject=subject,
            message=body,
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=[to_email],
            fail_silently=False,
        )
        return {"success": True, "to": to_email}
    except Exception as e:
        return {"success": False, "error": str(e)}