"""
email_agent.py
──────────────
Sends a formatted HTML patient report via Gmail SMTP.
Reads credentials from config.py (which reads from .env).
"""

import smtplib
from email.mime.text      import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime             import datetime

from config import SENDER_EMAIL, GMAIL_APP_PASSWORD, SMTP_SERVER, SMTP_PORT
from logger import log


def send_patient_report(
    recipient_email : str,
    question        : str,
    answer          : str,
    source          : dict,
    patient_name    : str = "Unknown Patient"
) -> bool:
    """
    Build and send a styled HTML email with the patient query result.

    Args:
        recipient_email : doctor / staff email address
        question        : original query
        answer          : LLM-generated answer
        source          : {"file": "...", "page": N}
        patient_name    : name extracted from context

    Returns:
        True  → email sent successfully
        False → sending failed (details logged)
    """

    if not SENDER_EMAIL or not GMAIL_APP_PASSWORD:
        log.error("SENDER_EMAIL or GMAIL_APP_PASSWORD not set in .env")
        return False

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    subject   = f"[Patient Report] {patient_name} — {datetime.now().strftime('%d %b %Y')}"

    # ── HTML email body ───────────────────────────────────────
    html = f"""
    <html>
    <body style="font-family:Arial,sans-serif;max-width:680px;margin:auto;color:#333;">

      <!-- Header -->
      <div style="background:#1a56a0;padding:20px 24px;border-radius:8px 8px 0 0;">
        <h2 style="color:#fff;margin:0;font-size:20px;">🏥 Patient Information Report</h2>
        <p  style="color:#c0d8f5;margin:6px 0 0;font-size:13px;">Generated: {timestamp}</p>
      </div>

      <!-- Details table -->
      <div style="border:1px solid #dce3ec;border-top:none;padding:24px;border-radius:0 0 8px 8px;">
        <table style="width:100%;border-collapse:collapse;margin-bottom:24px;font-size:14px;">
          <tr style="background:#f0f4fa;">
            <td style="padding:10px 14px;font-weight:bold;width:130px;color:#1a56a0;">Patient</td>
            <td style="padding:10px 14px;">{patient_name}</td>
          </tr>
          <tr>
            <td style="padding:10px 14px;font-weight:bold;color:#1a56a0;">Query</td>
            <td style="padding:10px 14px;">{question}</td>
          </tr>
          <tr style="background:#f0f4fa;">
            <td style="padding:10px 14px;font-weight:bold;color:#1a56a0;">Source File</td>
            <td style="padding:10px 14px;">{source.get("file", "N/A")}</td>
          </tr>
          <tr>
            <td style="padding:10px 14px;font-weight:bold;color:#1a56a0;">Page</td>
            <td style="padding:10px 14px;">{source.get("page", 0) + 1}</td>
          </tr>
        </table>

        <!-- Answer block -->
        <h3 style="color:#1a56a0;border-bottom:2px solid #1a56a0;padding-bottom:6px;font-size:16px;">
          Answer
        </h3>
        <div style="background:#f7f9fc;padding:16px;border-left:4px solid #1a56a0;
                    border-radius:4px;line-height:1.8;font-size:14px;">
          {answer.replace(chr(10), "<br>")}
        </div>

        <!-- Footer -->
        <p style="margin-top:28px;font-size:11px;color:#999;border-top:1px solid #eee;padding-top:12px;">
          ⚠️ Auto-generated by Patient RAG Agent. 
          Always verify with primary medical records before any clinical decision.
        </p>
      </div>

    </body>
    </html>
    """

    # ── Plain-text fallback ───────────────────────────────────
    plain = (
        f"Patient Report — {patient_name}\n"
        f"Generated : {timestamp}\n\n"
        f"Query     : {question}\n"
        f"Source    : {source.get('file','N/A')} | Page {source.get('page',0)+1}\n\n"
        f"Answer:\n{answer}\n\n"
        "[Auto-generated by Patient RAG Agent]"
    )

    # ── Build MIME message ────────────────────────────────────
    msg              = MIMEMultipart("alternative")
    msg["Subject"]   = subject
    msg["From"]      = SENDER_EMAIL
    msg["To"]        = recipient_email
    msg.attach(MIMEText(plain, "plain"))
    msg.attach(MIMEText(html,  "html"))   # email clients show HTML if supported

    # ── Send ──────────────────────────────────────────────────
    try:
        with smtplib.SMTP(SMTP_SERVER, SMTP_PORT) as server:
            server.ehlo()
            server.starttls()                                        # encrypt connection
            server.login(SENDER_EMAIL, GMAIL_APP_PASSWORD)
            server.sendmail(SENDER_EMAIL, recipient_email, msg.as_string())

        log.info(f"Email sent ✅ → {recipient_email}")
        return True

    except smtplib.SMTPAuthenticationError:
        log.error("Gmail auth failed — check SENDER_EMAIL and GMAIL_APP_PASSWORD in .env")
    except smtplib.SMTPException as e:
        log.error(f"SMTP error: {e}")
    except Exception as e:
        log.error(f"Unexpected email error: {e}")

    return False